// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrcfXSWwj4a5nn2WYBOC3kMmgFrVduNG0',
    appId: '1:773229696125:web:2800e4a18f069b065f4d14',
    messagingSenderId: '773229696125',
    projectId: 'ecommerceapp-46a27',
    authDomain: 'ecommerceapp-46a27.firebaseapp.com',
    storageBucket: 'ecommerceapp-46a27.firebasestorage.app',
    measurementId: 'G-1EVHCB0W6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEYZo1k4ltHnk2pAscacRU7sz1jJIbO7w',
    appId: '1:773229696125:android:f581aa47692ff6355f4d14',
    messagingSenderId: '773229696125',
    projectId: 'ecommerceapp-46a27',
    storageBucket: 'ecommerceapp-46a27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAefSS36sYWXpO5wAIBsYEFcWarFLXKuM',
    appId: '1:773229696125:ios:78d641b5fd7959ca5f4d14',
    messagingSenderId: '773229696125',
    projectId: 'ecommerceapp-46a27',
    storageBucket: 'ecommerceapp-46a27.firebasestorage.app',
    iosClientId: '773229696125-oafngapmpb66lasd3ljt54o6spo3uuef.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAefSS36sYWXpO5wAIBsYEFcWarFLXKuM',
    appId: '1:773229696125:ios:78d641b5fd7959ca5f4d14',
    messagingSenderId: '773229696125',
    projectId: 'ecommerceapp-46a27',
    storageBucket: 'ecommerceapp-46a27.firebasestorage.app',
    iosClientId: '773229696125-oafngapmpb66lasd3ljt54o6spo3uuef.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAdminPanel',
  );
}
